<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_eBayComprar por categor</name>
   <tag></tag>
   <elementGuidId>26b55c23-4d0c-41f2-ae50-042b6a641c3d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gh</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>banner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-w gh-simpleH</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>eBayComprar por categoríaComprar por categoríaArtículos de colección y arteObjetos de colecciónAntigüedadesMemorabilia deportivaArteTecnologíaComputadoras y tabletasCámaras y fotografíaTV, sistemas de audio y vigilanciaCelulares y accesoriosModaMujerHombreJoyería y relojesCalzadoHogar y jardínArtículos para el jardín y exterioresArtesaníasMejoras al hogarProductos para mascotasMotoresPiezas y accesoriosAutos y camionetasMotocicletasOtros vehículosInstrumentos y equipos musicalesGuitarraEquipo de audio profesionalCuerdasIluminación y efectos de escenarioArtículos deportivosDeportes al aire libreDeportes en equipoEjercicio y condición físicaGolfJuguetes y pasatiemposControl por radio y mandoVehículos de presofusión y de jugueteFiguras de acciónMuñecas y ososOtras categoríasVideojuegos y consolasSalud y bellezaBebésEquipo y maquinaria industrialVer todas las categoríasIngresa la palabra clave de búsquedapumapuma shoespuma knifepuma suedepuma ferraripuma golf shoespuma romapuma bmwpuma fentypuma fierceOcultar sugerencias de eBayTodas las categoríasAntigüedadesArteArtesaníaArtículos de colecciónArtículos deportivosArtículos para mascotasBebésBelleza y saludBienes raícesCámaras y fotografíaCelulares y accesoriosCerámica y cristalComputadoras, tablets y redesDVD y películaseBay MotorsEntradas, boletosEntretenimientoEquipo y maquinaria industrialHogar y jardínInstrumentos y equipos musicalesJoyas y relojesJuguetes y pasatiemposLibrosMemorabilia deportiva, cromos y artículos para aficionadosMonedas y billetesMuñecas y ososMúsicaRopa, zapatos y accesoriosSellosServicios especialesTarjetas de regalo y cuponesTecnologíaViajesVideojuegos y consolasTodo lo demásBúsqueda avanzada¡Hola! Inicia sesión o regístrate ebay Ofertas Vender Ayuda y contactoIdioma actual: EspañolEspañolEnglish Mi eBayExpandir Mi eBay Resumen Vistos recientemente Ofertas de subasta / Ofertas Lista de artículos que sigues Historial de compras Ventas Búsquedas guardadas Vendedores guardados MensajesNotificación</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gh&quot;)</value>
   </webElementProperties>
</WebElementEntity>
