<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblDescripcionProducto</name>
   <tag></tag>
   <elementGuidId>29c9243a-c3f2-49b4-8e06-57ea50a02d2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='srp-river-results-listing${indexProd}']/div/div[2]/a/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='srp-river-results-listing${indexProd}']/div/div[2]/a/h3</value>
   </webElementProperties>
</WebElementEntity>
