<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblEnvio</name>
   <tag></tag>
   <elementGuidId>7a56edbd-a0de-4c0f-916e-6e114d95c504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='srp-river-results-listing${indexEnvio}']/div/div[2]/div[3]/div[3]/span</value>
   </webElementProperties>
</WebElementEntity>
